version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kv-storage-app
    ports:
      - "8080:8080"
    environment:
      - TARANTOOL_HOST=tarantool
    depends_on:
      tarantool:
        condition: service_healthy

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua
      - ./tarantool/healthcheck.lua:/opt/tarantool/healthcheck.lua
    healthcheck:
      test: ["CMD", "tarantool", "/opt/tarantool/healthcheck.lua"]
      interval: 5s
      timeout: 5s
      retries: 5

  tarantool-admin:
    image: tarantool/tarantool:latest
    ports:
      - "8082:8081"
    command: tarantool -e "require('http.server').new({host = '0.0.0.0', port = 8081}):start()"
    depends_on:
      - tarantool