version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: songs-store-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c "
      /usr/local/bin/migrate -path /app/schema -database postgres://postgres:postgres@db:5432/songs-store-db?sslmode=disable up &&
      ./main
      "