version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TARANTOOL_HOST=tarantool

  tarantool:
    image: tarantool/tarantool:2.10
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
     - ./backend/init.lua:/opt/tarantool/init.lua